import com.uberkautilya.learndrools.model.Order;

rule "HDFC"

when
orderObject : Order(cardProvider=="HDFC" && price>10000)
then
orderObject.setDiscount(10);
end;

rule "ICICI"

when
orderObject : Order(cardProvider=="ICICI" && price>15000)
then
orderObject.setDiscount(15);
end;

rule "Federal Bank"

when
orderObject : Order(cardProvider=="Federal Bank" && price>10000)
then
orderObject.setDiscount(12);
end;